python main.py\
    --bits 128\
    --ilsvrc_data_dir /dataset/ILSVRC2012\
    --cifar_data_dir /dataset/cifar-10\
    --nuswide_data_dir /dataset/nus-wide\
    --batch_size 128\
    --sample_per_class 8\
    --eval_step 1\
    --fp16\
    --no_save\
    --lr 1e-2\
    --margin 1.0 \
